---
- name: Install and Configure Tomcat on Amazon Linux 2023 with Corretto 17
  hosts: webservers
  become: yes

  vars:
    tomcat_version: "9.0.109"
    tomcat_install_dir: "/opt/tomcat"

  tasks:
    - name: Ensure system is updated
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Amazon Corretto 17 (headless)
      yum:
        name: java-17-amazon-corretto-headless
        state: present

    - name: Create tomcat group
      group:
        name: tomcat
        state: present

    - name: Create tomcat user
      user:
        name: tomcat
        group: tomcat
        home: "{{ tomcat_install_dir }}"
        shell: /bin/nologin
        state: present
        create_home: yes

    - name: Ensure tomcat install directory exists
      file:
        path: "{{ tomcat_install_dir }}"
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"

    - name: Extract Tomcat
      unarchive:
        src: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: "{{ tomcat_install_dir }}"
        remote_src: yes
        owner: tomcat
        group: tomcat
        extra_opts: [--strip-components=1]

    - name: Ensure Tomcat temp directory exists
      file:
        path: "{{ tomcat_install_dir }}/temp"
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Configure Tomcat users for manager access
      copy:
        dest: "{{ tomcat_install_dir }}/conf/tomcat-users.xml"
        content: |
          <?xml version="1.0" encoding="UTF-8"?>
          <tomcat-users xmlns="http://tomcat.apache.org/xml"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                        version="1.0">
              <role rolename="manager-gui"/>
              <role rolename="manager-script"/>
              <role rolename="manager-status"/>
              <role rolename="admin-gui"/>
              <role rolename="admin-script"/>
              <user username="admin" password="khushal123" roles="manager-gui,manager-script,manager-status,admin-gui,admin-script"/>
          </tomcat-users>
        owner: tomcat
        group: tomcat
        mode: '0640'

    - name: Allow remote access to manager and host-manager apps
      replace:
        path: "{{ tomcat_install_dir }}/webapps/{{ item }}/META-INF/context.xml"
        regexp: '(<Valve.*RemoteAddrValve.*>)'
        replace: '<!-- \1 -->'
      loop:
        - manager
        - host-manager
      notify: Restart Tomcat

    - name: Set correct ownership for all Tomcat files
      file:
        path: "{{ tomcat_install_dir }}"
        owner: tomcat
        group: tomcat
        recurse: yes

    - name: Make all Tomcat scripts executable
      file:
        path: "{{ tomcat_install_dir }}/bin"
        recurse: yes
        state: directory
        mode: '0755'

    - name: Create Tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Server
          After=network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat
          Environment="JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto"
          Environment="CATALINA_PID={{ tomcat_install_dir }}/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ tomcat_install_dir }}"
          Environment="CATALINA_BASE={{ tomcat_install_dir }}"
          ExecStart={{ tomcat_install_dir }}/bin/startup.sh
          ExecStop={{ tomcat_install_dir }}/bin/shutdown.sh
          ExecReload=/bin/bash -c '{{ tomcat_install_dir }}/bin/shutdown.sh && {{ tomcat_install_dir }}/bin/startup.sh'

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start Tomcat

  handlers:
    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes
